let greeting = 'hello';
console.log(greeting);
let name = 'owu';
console.log(name);
let com = 'com';
console.log(com);
let country = 'ua';
console.log(country);
let one = 1;
console.log(one);
let ten = 10;
console.log(ten);
let minusNumber = -999;
console.log(minusNumber);
let oneTwoThree = 123;
console.log(oneTwoThree);
let pi = 3.14;
console.log(pi);
let twoSeven = 2.7;
console.log(twoSeven);
let sixteen =16;
console.log(sixteen);
let booleanTrue = true;
let booleanFalse = false;
console.log(booleanTrue, booleanFalse);

let firstName = 'Krotko';
let middleName = 'Daryna';
let lastName = 'Olegivna';
let person = `${firstName} ${middleName} ${lastName}`;
console.log(person);
let a = 100;
console.log(100, typeof 100);
let b = '100';
console.log('100', typeof '100');
let c = true;
console.log( c, typeof c);

const name1 = prompt('Як мене звати?', 'Дарина');
const middlename = prompt('Як мене по-батькові?', 'Олегівна');
const age = +prompt('Скільки мені років?', '22');
console.log(name1, middlename, age);